# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
# Skip prepare scripts, install dependencies
RUN npm install --ignore-scripts

# Copy source files
COPY tsconfig.json .
COPY src ./src

# Build the project
RUN npm run build

# Expose no port since stdio

# Default command
CMD ["node", "build/index.js"]
